language: bash

services:
  - docker

env:
  global:
    - IMAGE_NAME=${DOCKERHUB_USER}/nlp4re

script:
  - docker build -t ${IMAGE_NAME} .

deploy:
  - provider: script
    script: 
      docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PW} && docker push ${IMAGE_NAME}
    on:
      branch: master
  
  - provider: script
    script: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PW} && docker tag ${IMAGE_NAME} 
    on:
      tags: true