# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NLP4RE

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
    env:
      DATABASE_PORT: 3306
      DATABASE_HOST: localhost    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: start mysql
      run: sudo systemctl start mysql.service 
    - name: Build with Maven
      run: mvn -B clean package -DskipTests=true --file pom.xml 
  coverage:
    needs: build
    runs-on: ubuntu-latest
    env:
      DATABASE_PORT: 3306
      DATABASE_HOST: localhost   
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
         java-version: 11
    - name: start mysql
      run: sudo systemctl start mysql.service
    - name: Run test and create report
      run: mvn test jacoco:report
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)

  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_PORT: 3306
      DBHOST: nlp4re_mysql
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
       
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
 
      - name: create network for communication with mysql-container
        run: docker network create nlp4reNet-mysql
      
      - name: pull mysql
        run: docker pull mysql:8.0

      - name: start mysql docker container
        run: docker run -p 33306:3306 --name ${DBHOST} --network nlp4reNet-mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_ROOT_USER=root -e MYSQL_DATABASE=nlp4re -d mysql:8.0

      - name: Build docker image
        run: docker build -f ./Dockerfile --network  nlp4reNet-mysql --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/nlp4re:latest  .

      - name: push docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nlp4re:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
