# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NLP4RE

on:
  push:
    branches: [ add_new_rules]
  pull_request:
    branches: [ master ]
services:
  mysql:
    image: mysql:5.7
    env:
      MYSQL_DATABASE: nlp4re
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33306:3306
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: set up mysql
      run: |
      	sudo /etc/init.d/mysql start
      	mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }}
    - name: Build with Maven
      run: mvn clean package --file pom.xml

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
         java-version: 11
    - name: set up mysql
      run: |
      	sudo /etc/init.d/mysql start
      	mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }}
    - name: Run test and create report
      run: mvn test jacoco:report
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
      
