# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NLP4RE

on:
  push:
    branches: [ add_new_rules]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
    env:
      MYSQL_DATABASE: nlp4re
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: start mysql
      run: sudo systemctl start mysql.service
    - name: Create sql database
      run: mysqladmin -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }} CREATE DATABASE ${{ env.MYSQL_DATABASE }}
    - run: mysql show databases;
    - name: Build with Maven
      run: mvn clean package --file pom.xml

  coverage:
    needs: build
    runs-on: ubuntu-latest
    env:
      MYSQL_DATABASE: nlp4re
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
         java-version: 11
    - name: start mysql
      run: sudo systemctl start mysql.service
    - name: Create sql database
      run: mysqladmin -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_ROOT_PASSWORD }} CREATE DATABASE ${{ env.MYSQL_DATABASE }}
    - name: Run test and create report
      run: mvn test jacoco:report
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
      
