# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NLP4RE

on:
  push:
    branches: [ add_new_rules]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        java-version: ${{ matrix.java-version }}
	mysql-version: '8.0'
    - name: set up mysql
      run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
    - name: Build with Maven
      run: mvn clean package --file pom.xml

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
         java-version: 11
         mysql-version: '8.0'
    - name: Run test and create report
      run: mvn test jacoco:report
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
      
